### Задание 1
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк
и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6,
8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива
Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемнта.

In [2]:
import numpy as np
import pandas as pd

In [3]:
a = np.array([1, 2, 3, 3, 1, 6, 8, 11, 10, 7]).reshape(2, 5).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения
соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно
производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [6]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна
получиться величина _centered_spa. Затем поделите a_centered_sp на N-1, где N - число
наблюдений.

In [8]:
df = pd.DataFrame(a_centered)
df

0    1
0 -1.0 -2.4
1  0.0 -0.4
2  1.0  2.6
3  1.0  1.6
4 -1.0 -1.4

In [9]:
_centered_spa = np.dot(df[0], df[1])
_centered_spa

8.0

In [10]:
_centered_spa/(df.shape[0] * df.shape[1]-1)

0.8888888888888888

### Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся
в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на
N, поэтому полученная нами величина является несмещенной оценкой ковариации.

In [12]:
np.cov(a)

array([[12.5, 15. , 20. , 17.5, 15. ],
       [15. , 18. , 24. , 21. , 18. ],
       [20. , 24. , 32. , 28. , 24. ],
       [17.5, 21. , 28. , 24.5, 21. ],
       [15. , 18. , 24. , 21. , 18. ]])

# Тема “Работа с данными в Pandas”

### Задание 1

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со
столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и
['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно
содержатся данные:
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и
поклонники']
Нужны prices!
[500, 400, 300, 350, 450, 600, 200]

In [16]:
authors = pd.DataFrame({'author_id' : [1, 2, 3],
                        'author_name' : ['Тургенев', 'Чехов', 'Островский']
                        })

In [17]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [18]:
book = pd.DataFrame({'author_id' : [1, 1, 1, 2, 2, 3, 3],
                     'book_title' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price' : [500, 400, 300, 350, 450, 600, 200]
                    })

In [19]:
book

author_id            book_title  price
0          1           Отцы и дети    500
1          1                 Рудин    400
2          1     Дворянское гнездо    300
3          2      Толстый и тонкий    350
4          2       Дама с собачкой    450
5          3                 Гроза    600
6          3  Таланты и поклонники    200

### Задание 2
Получите датафрейм authors_price, соединив дата фреймы authors и books по полю author_id.

In [21]:
authors_price = authors.merge(book, left_on='author_id', right_on='author_id', suffixes=(False, False))
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    500
1          1    Тургенев                 Рудин    400
2          1    Тургенев     Дворянское гнездо    300
3          2       Чехов      Толстый и тонкий    350
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    600
6          3  Островский  Таланты и поклонники    200

### Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими
книгами.

In [23]:
authors_price.nlargest(5, ['price']) 

author_id author_name        book_title  price
5          3  Островский             Гроза    600
0          1    Тургенев       Отцы и дети    500
4          2       Чехов   Дама с собачкой    450
1          1    Тургенев             Рудин    400
3          2       Чехов  Толстый и тонкий    350

### Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat
должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя
цена на книги этого автора.
на книги этого автора.

In [25]:
authors_stat = pd.DataFrame({
    'author_name' :  authors_price['author_name'],
    'price_min' : authors_price['price'].min(),
    'price_max' : authors_price['price'].max(),
    'price_mean' : authors_price['price'].mean()
})
authors_stat

author_name  price_min  price_max  price_mean
0    Тургенев        200        600       400.0
1    Тургенев        200        600       400.0
2    Тургенев        200        600       400.0
3       Чехов        200        600       400.0
4       Чехов        200        600       400.0
5  Островский        200        600       400.0
6  Островский        200        600       400.0

### Задание 5**

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться
данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные
из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot table с помощью вопросительного знака.
Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте
для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а
индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями,
при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием
"book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь,
что датафреймы book_info и book_info2 идентичны.

In [27]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    500  твердая
1          1    Тургенев                 Рудин    400   мягкая
2          1    Тургенев     Дворянское гнездо    300   мягкая
3          2       Чехов      Толстый и тонкий    350  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    600   мягкая
6          3  Островский  Таланты и поклонники    200   мягкая

In [28]:
pd.pivot_table?

Signature:
pd.pivot_table(
    data: 'DataFrame',
    values=None,
    index=None,
    columns=None,
    aggfunc: 'AggFuncType' = 'mean',
    fill_value=None,
    margins: 'bool' = False,
    dropna: 'bool' = True,
    margins_name: 'Hashable' = 'All',
    observed: 'bool' = False,
    sort: 'bool' = True,
) -> 'DataFrame'
Docstring:
Create a spreadsheet-style pivot table as a DataFrame.

The levels in the pivot table will be stored in MultiIndex objects
(hierarchical indexes) on the index and columns of the result DataFrame.

Parameters
----------
data : DataFrame
values : list-like or scalar, optional
    Column or columns to aggregate.
index : column, Grouper, array, or list of the previous
    Keys to group by on the pivot table index. If a list is passed,
    it can contain any of the other types (except list). If an array is
    passed, it must be the same length as the data and will be used in
    the same manner as column values.
columns : column, Grouper, array, or list of the

In [29]:
book_info = pd.pivot_table(authors_price,  values='price', index=['author_name'], columns=['cover'], 
                           aggfunc="sum", fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      800        0
Тургенев        700      500
Чехов             0      800

In [49]:
book_info.to_pickle("book_info.pkl")

In [53]:
book_info2 = pd.read_pickle("book_info.pkl")
book_info2

cover        мягкая  твердая
author_name                 
Островский      800        0
Тургенев        700      500
Чехов             0      800